// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Ptk1InS5t0xJmPNrG27Utx5uQhnpTk4',
    appId: '1:524738435081:web:ab72b1a5cfc315e1f2c0d8',
    messagingSenderId: '524738435081',
    projectId: 'tepflutter',
    authDomain: 'tepflutter.firebaseapp.com',
    storageBucket: 'tepflutter.appspot.com',
    measurementId: 'G-X55XWQY9HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfmMmUK9G170lQIiGdyY_YUkyIomhxapY',
    appId: '1:524738435081:android:1e0b5bcce3b51711f2c0d8',
    messagingSenderId: '524738435081',
    projectId: 'tepflutter',
    storageBucket: 'tepflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2XgY8gYH7BvQolgFmB8JBtxRzFYfhNFg',
    appId: '1:524738435081:ios:5f6345f0298ef702f2c0d8',
    messagingSenderId: '524738435081',
    projectId: 'tepflutter',
    storageBucket: 'tepflutter.appspot.com',
    iosClientId: '524738435081-u3fc4vmi83katd4ib2ga435h8suhah3d.apps.googleusercontent.com',
    iosBundleId: 'iailab.tepFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2XgY8gYH7BvQolgFmB8JBtxRzFYfhNFg',
    appId: '1:524738435081:ios:5f6345f0298ef702f2c0d8',
    messagingSenderId: '524738435081',
    projectId: 'tepflutter',
    storageBucket: 'tepflutter.appspot.com',
    iosClientId: '524738435081-u3fc4vmi83katd4ib2ga435h8suhah3d.apps.googleusercontent.com',
    iosBundleId: 'iailab.tepFlutter',
  );
}
